# Generated by Django 6.0.5 on 2026-05-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='video_path',
            field=models.TextField(blank=True, default=''),
        ),
    ]
