# Generated by Django 6.0.5 on 2026-05-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog_image_path_blog_video_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='..\\assests\\images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='video_path',
            field=models.FileField(blank=True, upload_to='..\\assests\\videos'),
        ),
    ]
