# Generated by Django 6.0.5 on 2026-05-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_blog_image_path_alter_blog_video_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='video_path',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
